version: 2.1

jobs:
    build_app:
        docker:
            - image: python:3.7.3-stretch
        working_directory: ~/app
        steps:
            - checkout
            - run:
                name: "Install dependencies"
                command: |
                    python3 -m venv ~/.capstoneenv
                    . ~/.capstoneenv/bin/activate
                    make install
            - run:
                name: "Lint Python script and Dockerfile"
                command: |
                    . ~/.capstoneenv/bin/activate
                    make lint
    create_docker_image:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: "Create docker image"
                command: |
                    bash shell_scripts/build_image.sh
    publish_docker_image:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: "Publish docker image to Docker Hub Repository"
                command: |
                    bash shell_scripts/upload_image.sh "xyz"
                    
workflows:
    default:
        jobs:
            - create_and_push_docker_image
                    
                
            