version: 2.1

orbs:
    aws-cli: circleci/aws-cli@2.0.6
    aws-eks: circleci/aws-eks@2.2.0
    kubernetes: circleci/kubernetes@1.3

jobs:
    build_app:
        docker:
            - image: python:3.7.3-stretch
        steps:
            - checkout
            - run:
                name: "Install dependencies"
                command: |
                    python3 -m venv ~/.capstoneenv
                    . ~/.capstoneenv/bin/activate
                    make install
            - run:
                name: "Lint Python script and Dockerfile"
                command: |
                    . ~/.capstoneenv/bin/activate
                    make lint
    create_docker_image:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: "Create docker image"
                command: |
                    bash shell_scripts/build_image.sh
            - run:
                name: "Archive docker image"
                command: docker save -o image.tar gsindhwani/sample-capstone-app
            - persist_to_workspace:
                root: .
                paths: ./image.tar
    publish_docker_image:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - setup_remote_docker
            - attach_workspace:
                at: /tmp/workspace
            - run:
                name: "Load archived image"
                command: docker load -i /tmp/workspace/image.tar
            - run:
                name: "Publish docker image to Docker Hub Repository"
                command: bash shell_scripts/upload_image.sh $DOCKER_HUB_PASS
                    
workflows:
    default:
        jobs:
            - aws-cli/setup:
                aws-access-key-id: AKIA4Y2WNE4DASVGPE6A
                aws-secret-access-key: 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
                aws-region: us-east-1
            - aws-eks/create-cluster:
                cluster-name: my-eks-demo
                aws-profile: capstone_user
                    
                
            