version: 2.1

jobs:
    build_app:
        docker:
            - image: python:3.7.3-stretch
        working_directory: ~/app
        steps:
            - checkout
            - run:
                name: "Install dependencies"
                command: |
                    python3 -m venv ~/.capstoneenv
                    . ~/.capstoneenv/bin/activate
                    make install
            - run:
                name: "Lint Python script and Dockerfile"
                command: |
                    . ~/.capstoneenv/bin/activate
                    make lint
    create_docker_image:
        docker:
            - image: cimg/base:2022.06
        steps:
            - checkout
            - setup_remote_docker:
                version: 20.10.14
            - run:
                name: "Create docker image"
                command: |
                    ls
                    docker build -t sample-app .
                    docker images
                    
workflows:
    default:
        jobs:
            - create_docker_image
                    
                
            