apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-capstone-app-updated
  template:
    metadata:
      labels:
        app: sample-capstone-app-updated
    spec:
      containers:
        - name: back-end
          image: gsindhwani/sample-capstone-app-updated
          ports:
            - containerPort: 8080